<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Pengawasan;
use App\Models\User;
use App\Models\MasterJenisPanganSegar;
use App\Models\MasterBahanPanganSegar;
use App\Models\MasterKota;
use App\Models\MasterProvinsi;
use Illuminate\Support\Str;
use Carbon\Carbon;

class PengawasanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get reference data
        $users = User::pluck('id', 'email')->toArray();
        $jenisPangan = MasterJenisPanganSegar::pluck('id', 'kode_jenis_pangan_segar')->toArray();
        $bahanPangan = MasterBahanPanganSegar::pluck('id', 'kode_bahan_pangan_segar')->toArray();
        $kotas = MasterKota::pluck('id', 'nama_kota')->toArray();
        $provinsis = MasterProvinsi::pluck('id', 'nama_provinsi')->toArray();

        // Group pengawasan data by province, product type, and time range for aggregation
        $pengawasanGroupedByProvinceProduct = [
            // Jawa Tengah - Kentang (BP035) - Recent period
            'jateng_kentang_recent' => [
                [
                    'id' => Str::uuid(),
                    'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                    'lokasi_alamat' => 'Jl. Sudirman No. 123, Semarang',
                    'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                    'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                    'tanggal_mulai' => Carbon::now()->subDays(10),
                    'tanggal_selesai' => Carbon::now()->subDays(5),
                    'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                    'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                    'hasil_pengawasan' => 'Pemeriksaan rutin berjalan lancar, tidak ditemukan pelanggaran.',
                    'lampiran1' => 'files/upload/lampiran1_sample1.pdf',
                    'lampiran2' => 'files/upload/lampiran2_sample1.pdf',
                    'lampiran3' => 'files/upload/lampiran3_sample1.pdf',
                    'lampiran4' => 'files/upload/lampiran4_sample1.pdf',
                    'lampiran5' => 'files/upload/lampiran5_sample1.pdf',
                    'lampiran6' => 'files/upload/lampiran6_sample1.pdf',
                    'status' => 'SELESAI',
                    'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                    'is_active' => true,
                    'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                    'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                ],
                [
                    'id' => Str::uuid(),
                    'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                    'lokasi_alamat' => 'Jl. Pemuda No. 78, Kota Semarang',
                    'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                    'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                    'tanggal_mulai' => Carbon::now()->subDays(20),
                    'tanggal_selesai' => Carbon::now()->subDays(15),
                    'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                    'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                    'hasil_pengawasan' => 'Pemeriksaan rutin menunjukkan kualitas kentang dalam kondisi baik.',
                    'lampiran1' => 'files/upload/lampiran1_sample6.pdf',
                    'lampiran2' => 'files/upload/lampiran2_sample6.pdf',
                    'lampiran3' => 'files/upload/lampiran3_sample6.pdf',
                    'lampiran4' => 'files/upload/lampiran4_sample6.pdf',
                    'lampiran5' => 'files/upload/lampiran5_sample6.pdf',
                    'lampiran6' => 'files/upload/lampiran6_sample6.pdf',
                    'status' => 'SELESAI',
                    'tindakan_rekomendasikan' => 'Melakukan kontrol kualitas rutin untuk mempertahankan standar.',
                    'is_active' => true,
                    'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                    'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                ],
                [
                    'id' => Str::uuid(),
                    'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                    'lokasi_alamat' => 'Jl. Soekarno Hatta No. 345, Kota Semarang',
                    'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                    'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                    'tanggal_mulai' => Carbon::now()->subDays(35),
                    'tanggal_selesai' => Carbon::now()->subDays(30),
                    'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                    'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                    'hasil_pengawasan' => 'Kentang dalam kondisi baik, sesuai standar.',
                    'lampiran1' => 'files/upload/lampiran1_sample12.pdf',
                    'lampiran2' => 'files/upload/lampiran2_sample12.pdf',
                    'lampiran3' => 'files/upload/lampiran3_sample12.pdf',
                    'lampiran4' => 'files/upload/lampiran4_sample12.pdf',
                    'lampiran5' => 'files/upload/lampiran5_sample12.pdf',
                    'lampiran6' => 'files/upload/lampiran6_sample12.pdf',
                    'status' => 'SELESAI',
                    'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                    'is_active' => true,
                    'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                    'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                ],
            ],
            // Jawa Timur - Ubi Jalar (BP135) - Recent period
            'jatim_ubijalar_recent' => [
                [
                    'id' => Str::uuid(),
                    'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                    'lokasi_alamat' => 'Jl. Gatot Subroto No. 456, Kota Surabaya',
                    'lokasi_kota_id' => $kotas['Kota Surabaya'] ?? null,
                    'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                    'tanggal_mulai' => Carbon::now()->subDays(8),
                    'tanggal_selesai' => Carbon::now()->subDays(3),
                    'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                    'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                    'hasil_pengawasan' => 'Ditemukan cemaran mikroba dalam batas aman, namun perbaikan sanitasi diperlukan.',
                    'lampiran1' => 'files/upload/lampiran1_sample2.pdf',
                    'lampiran2' => 'files/upload/lampiran2_sample2.pdf',
                    'lampiran3' => 'files/upload/lampiran3_sample2.pdf',
                    'lampiran4' => 'files/upload/lampiran4_sample2.pdf',
                    'lampiran5' => 'files/upload/lampiran5_sample2.pdf',
                    'lampiran6' => 'files/upload/lampiran6_sample2.pdf',
                    'status' => 'SELESAI',
                    'tindakan_rekomendasikan' => 'Melakukan perbaikan sistem sanitasi dan pelatihan karyawan.',
                    'is_active' => true,
                    'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                    'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                ],
                [
                    'id' => Str::uuid(),
                    'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                    'lokasi_alamat' => 'Jl. Gajah Mada No. 89, Kota Surabaya',
                    'lokasi_kota_id' => $kotas['Kota Surabaya'] ?? null,
                    'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                    'tanggal_mulai' => Carbon::now()->subDays(18),
                    'tanggal_selesai' => Carbon::now()->subDays(13),
                    'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                    'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                    'hasil_pengawasan' => 'Terdapat kebutuhan pelatihan sanitasi bagi karyawan.',
                    'lampiran1' => 'files/upload/lampiran1_sample7.pdf',
                    'lampiran2' => 'files/upload/lampiran2_sample7.pdf',
                    'lampiran3' => 'files/upload/lampiran3_sample7.pdf',
                    'lampiran4' => 'files/upload/lampiran4_sample7.pdf',
                    'lampiran5' => 'files/upload/lampiran5_sample7.pdf',
                    'lampiran6' => 'files/upload/lampiran6_sample7.pdf',
                    'status' => 'SELESAI',
                    'tindakan_rekomendasikan' => 'Melakukan pelatihan karyawan mengenai hygiene dan sanitasi.',
                    'is_active' => true,
                    'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                    'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                ],
                [
                    'id' => Str::uuid(),
                    'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                    'lokasi_alamat' => 'Jl. Tunjungan No. 678, Kota Surabaya',
                    'lokasi_kota_id' => $kotas['Kota Surabaya'] ?? null,
                    'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                    'tanggal_mulai' => Carbon::now()->subDays(32),
                    'tanggal_selesai' => Carbon::now()->subDays(27),
                    'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                    'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                    'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, tidak ada ditemukan masalah.',
                    'lampiran1' => 'files/upload/lampiran1_sample13.pdf',
                    'lampiran2' => 'files/upload/lampiran2_sample13.pdf',
                    'lampiran3' => 'files/upload/lampiran3_sample13.pdf',
                    'lampiran4' => 'files/upload/lampiran4_sample13.pdf',
                    'lampiran5' => 'files/upload/lampiran5_sample13.pdf',
                    'lampiran6' => 'files/upload/lampiran6_sample13.pdf',
                    'status' => 'SELESAI',
                    'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                    'is_active' => true,
                    'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                    'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                ],
            ],
            // Jawa Barat - Kentang (BP035) - Recent period
            'jabar_kentang_recent' => [
                [
                    'id' => Str::uuid(),
                    'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                    'lokasi_alamat' => 'Jl. Raya Bogor Km. 25, Kota Depok',
                    'lokasi_kota_id' => $kotas['Kota Depok'] ?? null,
                    'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                    'tanggal_mulai' => Carbon::now()->subDays(15),
                    'tanggal_selesai' => Carbon::now()->subDays(10),
                    'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                    'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                    'hasil_pengawasan' => 'Pemeriksaan menunjukkan kepatuan standar operasional prosedur yang baik.',
                    'lampiran1' => 'files/upload/lampiran1_sample3.pdf',
                    'lampiran2' => 'files/upload/lampiran2_sample3.pdf',
                    'lampiran3' => 'files/upload/lampiran3_sample3.pdf',
                    'lampiran4' => 'files/upload/lampiran4_sample3.pdf',
                    'lampiran5' => 'files/upload/lampiran5_sample3.pdf',
                    'lampiran6' => 'files/upload/lampiran6_sample3.pdf',
                    'status' => 'SELESAI',
                    'tindakan_rekomendasikan' => 'Mempertahankan kinerja yang baik dan terus meningkatkan kualitas.',
                    'is_active' => true,
                    'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                    'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                ],
                [
                    'id' => Str::uuid(),
                    'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                    'lokasi_alamat' => 'Jl. Ahmad Yani No. 78, Kota Bandung',
                    'lokasi_kota_id' => $kotas['Kota Bandung'] ?? null,
                    'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                    'tanggal_mulai' => Carbon::now()->subDays(5),
                    'tanggal_selesai' => Carbon::now()->subDays(2),
                    'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                    'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                    'hasil_pengawasan' => 'Terdapat kekurangan dokumentasi pelabelan produk.',
                    'lampiran1' => 'files/upload/lampiran1_sample4.pdf',
                    'lampiran2' => 'files/upload/lampiran2_sample4.pdf',
                    'lampiran3' => 'files/upload/lampiran3_sample4.pdf',
                    'lampiran4' => 'files/upload/lampiran4_sample4.pdf',
                    'lampiran5' => 'files/upload/lampiran5_sample4.pdf',
                    'lampiran6' => 'files/upload/lampiran6_sample4.pdf',
                    'status' => 'SELESAI',
                    'tindakan_rekomendasikan' => 'Melengkapi semua dokumen pelabelan sesuai standar.',
                    'is_active' => true,
                    'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                    'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                ],
                [
                    'id' => Str::uuid(),
                    'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                    'lokasi_alamat' => 'Jl. Asia Afrika No. 45, Kota Bandung',
                    'lokasi_kota_id' => $kotas['Kota Bandung'] ?? null,
                    'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                    'tanggal_mulai' => Carbon::now()->subDays(25),
                    'tanggal_selesai' => Carbon::now()->subDays(20),
                    'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                    'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                    'hasil_pengawasan' => 'Pemeriksaan laboratorium menunjukkan hasil normal untuk kentang.',
                    'lampiran1' => 'files/upload/lampiran1_sample8.pdf',
                    'lampiran2' => 'files/upload/lampiran2_sample8.pdf',
                    'lampiran3' => 'files/upload/lampiran3_sample8.pdf',
                    'lampiran4' => 'files/upload/lampiran4_sample8.pdf',
                    'lampiran5' => 'files/upload/lampiran5_sample8.pdf',
                    'lampiran6' => 'files/upload/lampiran6_sample8.pdf',
                    'status' => 'SELESAI',
                    'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                    'is_active' => true,
                    'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                    'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                ],
            ],
        ];

        // Flatten grouped data for insertion
        $pengawasanData = [];
        foreach ($pengawasanGroupedByProvinceProduct as $group) {
            $pengawasanData = array_merge($pengawasanData, $group);
        }

        // Additional pengawasan data
        $additionalPengawasanData = [
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Pemuda No. 78, Kota Semarang',
                'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(20),
                'tanggal_selesai' => Carbon::now()->subDays(15),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Pemeriksaan rutin menunjukkan kualitas kentang dalam kondisi baik.',
                'lampiran1' => 'files/upload/lampiran1_sample6.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample6.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample6.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample6.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample6.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample6.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melakukan kontrol kualitas rutin untuk mempertahankan standar.',
                'is_active' => true,
                'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Gajah Mada No. 89, Kota Surabaya',
                'lokasi_kota_id' => $kotas['Kota Surabaya'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(18),
                'tanggal_selesai' => Carbon::now()->subDays(13),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Terdapat kebutuhan pelatihan sanitasi bagi karyawan.',
                'lampiran1' => 'files/upload/lampiran1_sample7.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample7.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample7.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample7.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample7.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample7.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melakukan pelatihan karyawan mengenai hygiene dan sanitasi.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Asia Afrika No. 45, Kota Bandung',
                'lokasi_kota_id' => $kotas['Kota Bandung'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(25),
                'tanggal_selesai' => Carbon::now()->subDays(20),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Pemeriksaan laboratorium menunjukkan hasil normal untuk kentang.',
                'lampiran1' => 'files/upload/lampiran1_sample8.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample8.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample8.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample8.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample8.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample8.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Ahmad Yani No. 234, Kota Semarang',
                'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(22),
                'tanggal_selesai' => Carbon::now()->subDays(17),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Kualitas produk umbi dalam kondisi baik, sesuai standar.',
                'lampiran1' => 'files/upload/lampiran1_sample9.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample9.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample9.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample9.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample9.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample9.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Diponegoro No. 56, Kota Malang',
                'lokasi_kota_id' => $kotas['Kota Malang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(28),
                'tanggal_selesai' => Carbon::now()->subDays(23),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Ubi jalar dalam kondisi baik, tidak ada ditemukan masalah.',
                'lampiran1' => 'files/upload/lampiran1_sample10.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample10.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample10.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample10.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample10.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample10.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Raya Pajajaran No. 123, Kota Bogor',
                'lokasi_kota_id' => $kotas['Kota Bogor'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(30),
                'tanggal_selesai' => Carbon::now()->subDays(25),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, sesuai standar pangan.',
                'lampiran1' => 'files/upload/lampiran1_sample11.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample11.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample11.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample11.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample11.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample11.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Soekarno Hatta No. 345, Kota Semarang',
                'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(35),
                'tanggal_selesai' => Carbon::now()->subDays(30),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Kentang dalam kondisi baik, sesuai standar.',
                'lampiran1' => 'files/upload/lampiran1_sample12.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample12.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample12.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample12.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample12.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample12.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Tunjungan No. 678, Kota Surabaya',
                'lokasi_kota_id' => $kotas['Kota Surabaya'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(32),
                'tanggal_selesai' => Carbon::now()->subDays(27),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, tidak ada ditemukan masalah.',
                'lampiran1' => 'files/upload/lampiran1_sample13.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample13.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample13.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample13.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample13.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample13.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Merdeka No. 901, Kota Bandung',
                'lokasi_kota_id' => $kotas['Kota Bandung'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(38),
                'tanggal_selesai' => Carbon::now()->subDays(33),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Ubi jalar dalam kondisi baik, sesuai standar.',
                'lampiran1' => 'files/upload/lampiran1_sample14.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample14.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample14.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample14.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample14.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample14.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Pahlawan No. 234, Kota Semarang',
                'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(40),
                'tanggal_selesai' => Carbon::now()->subDays(35),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, sesuai standar pangan.',
                'lampiran1' => 'files/upload/lampiran1_sample15.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample15.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample15.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample15.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample15.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample15.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Basuki Rahmat No. 345, Kota Malang',
                'lokasi_kota_id' => $kotas['Kota Malang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(42),
                'tanggal_selesai' => Carbon::now()->subDays(37),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Kentang dalam kondisi baik, tidak ada ditemukan masalah.',
                'lampiran1' => 'files/upload/lampiran1_sample16.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample16.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample16.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample16.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample16.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample16.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Raya Bogor Km. 30, Kota Depok',
                'lokasi_kota_id' => $kotas['Kota Depok'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(45),
                'tanggal_selesai' => Carbon::now()->subDays(40),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, sesuai standar.',
                'lampiran1' => 'files/upload/lampiran1_sample17.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample17.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample17.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample17.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample17.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample17.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Sudirman No. 567, Kota Semarang',
                'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(48),
                'tanggal_selesai' => Carbon::now()->subDays(43),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Kentang dalam kondisi baik, sesuai standar pangan.',
                'lampiran1' => 'files/upload/lampiran1_sample18.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample18.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample18.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample18.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample18.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample18.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Tunjungan No. 890, Kota Surabaya',
                'lokasi_kota_id' => $kotas['Kota Surabaya'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(50),
                'tanggal_selesai' => Carbon::now()->subDays(45),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, tidak ada ditemukan masalah.',
                'lampiran1' => 'files/upload/lampiran1_sample19.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample19.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample19.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample19.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample19.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample19.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Asia Afrika No. 678, Kota Bandung',
                'lokasi_kota_id' => $kotas['Kota Bandung'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(52),
                'tanggal_selesai' => Carbon::now()->subDays(47),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Ubi jalar dalam kondisi baik, sesuai standar.',
                'lampiran1' => 'files/upload/lampiran1_sample20.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample20.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample20.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample20.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample20.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample20.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Pemuda No. 901, Kota Semarang',
                'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(55),
                'tanggal_selesai' => Carbon::now()->subDays(50),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, sesuai standar pangan.',
                'lampiran1' => 'files/upload/lampiran1_sample21.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample21.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample21.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample21.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample21.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample21.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Gajah Mada No. 123, Kota Surabaya',
                'lokasi_kota_id' => $kotas['Kota Surabaya'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(58),
                'tanggal_selesai' => Carbon::now()->subDays(53),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Kentang dalam kondisi baik, tidak ada ditemukan masalah.',
                'lampiran1' => 'files/upload/lampiran1_sample22.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample22.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample22.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample22.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample22.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample22.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Raya Pajajaran No. 456, Kota Bogor',
                'lokasi_kota_id' => $kotas['Kota Bogor'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(60),
                'tanggal_selesai' => Carbon::now()->subDays(55),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, sesuai standar.',
                'lampiran1' => 'files/upload/lampiran1_sample23.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample23.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample23.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample23.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample23.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample23.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Ahmad Yani No. 789, Kota Semarang',
                'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(65),
                'tanggal_selesai' => Carbon::now()->subDays(60),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Ubi jalar dalam kondisi baik, tidak ada ditemukan masalah.',
                'lampiran1' => 'files/upload/lampiran1_sample24.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample24.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample24.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample24.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample24.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample24.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Diponegoro No. 345, Kota Malang',
                'lokasi_kota_id' => $kotas['Kota Malang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(70),
                'tanggal_selesai' => Carbon::now()->subDays(65),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, sesuai standar pangan.',
                'lampiran1' => 'files/upload/lampiran1_sample25.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample25.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample25.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample25.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample25.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample25.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
            // Record for Kewenangan Pusat
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorpusat@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Kebon Sirih No. 50, Jakarta Pusat',
                'lokasi_kota_id' => $kotas['Kewenangan Pusat'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Kewenangan Pusat'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(5),
                'tanggal_selesai' => Carbon::now()->subDays(2),
                'jenis_psat_id' => $jenisPangan['JP001'] ?? null,
                'produk_psat_id' => $bahanPangan['BP001'] ?? null,
                'hasil_pengawasan' => 'Pemeriksaan rutin di kantor pusat berjalan lancar, tidak ditemukan pelanggaran.',
                'lampiran1' => 'files/upload/lampiran1_sample26.pdf',
                'lampiran2' => 'files/upload/lampiran2_sample26.pdf',
                'lampiran3' => 'files/upload/lampiran3_sample26.pdf',
                'lampiran4' => 'files/upload/lampiran4_sample26.pdf',
                'lampiran5' => 'files/upload/lampiran5_sample26.pdf',
                'lampiran6' => 'files/upload/lampiran6_sample26.pdf',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorpusat@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorpusat@panganaman.my.id'] ?? null,
            ],
        ];

        // Insert pengawasan data
        foreach (array_merge($pengawasanData, $additionalPengawasanData) as $data) {
            Pengawasan::create($data);
        }
    }
}

