<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Pengawasan;
use App\Models\User;
use App\Models\MasterJenisPanganSegar;
use App\Models\MasterBahanPanganSegar;
use App\Models\MasterKota;
use App\Models\MasterProvinsi;
use Illuminate\Support\Str;
use Carbon\Carbon;

class PengawasanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get reference data
        $users = User::pluck('id', 'email')->toArray();
        $jenisPangan = MasterJenisPanganSegar::pluck('id', 'kode_jenis_pangan_segar')->toArray();
        $bahanPangan = MasterBahanPanganSegar::pluck('id', 'kode_bahan_pangan_segar')->toArray();
        $kotas = MasterKota::pluck('id', 'nama_kota')->toArray();
        $provinsis = MasterProvinsi::pluck('id', 'nama_provinsi')->toArray();

        // Sample pengawasan data
        $pengawasanData = [
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Sudirman No. 123, Semarang',
                'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(10),
                'tanggal_selesai' => Carbon::now()->subDays(5),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Pemeriksaan rutin berjalan lancar, tidak ditemukan pelanggaran.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Gatot Subroto No. 456, Kota Surabaya',
                'lokasi_kota_id' => $kotas['Kota Surabaya'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(8),
                'tanggal_selesai' => Carbon::now()->subDays(3),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Ditemukan cemaran mikroba dalam batas aman, namun perbaikan sanitasi diperlukan.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melakukan perbaikan sistem sanitasi dan pelatihan karyawan.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Raya Bogor Km. 25, Kota Depok',
                'lokasi_kota_id' => $kotas['Kota Depok'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(15),
                'tanggal_selesai' => Carbon::now()->subDays(10),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Pemeriksaan menunjukkan kepatuan standar operasional prosedur yang baik.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Mempertahankan kinerja yang baik dan terus meningkatkan kualitas.',
                'is_active' => true,
                'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Ahmad Yani No. 78, Kota Bandung',
                'lokasi_kota_id' => $kotas['Kota Bandung'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(5),
                'tanggal_selesai' => Carbon::now()->subDays(2),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Terdapat kekurangan dokumentasi pelabelan produk.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melengkapi semua dokumen pelabelan sesuai standar.',
                'is_active' => true,
                'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Basuki Rahmat No. 12, Kota Malang',
                'lokasi_kota_id' => $kotas['Kota Malang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(12),
                'tanggal_selesai' => Carbon::now()->subDays(7),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Pemeriksaan laboratorium menunjukkan hasil normal.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
        ];

        // Additional pengawasan data
        $additionalPengawasanData = [
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Pemuda No. 78, Kota Semarang',
                'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(20),
                'tanggal_selesai' => Carbon::now()->subDays(15),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Pemeriksaan rutin menunjukkan kualitas kentang dalam kondisi baik.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melakukan kontrol kualitas rutin untuk mempertahankan standar.',
                'is_active' => true,
                'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Gajah Mada No. 89, Kota Surabaya',
                'lokasi_kota_id' => $kotas['Kota Surabaya'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(18),
                'tanggal_selesai' => Carbon::now()->subDays(13),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Terdapat kebutuhan pelatihan sanitasi bagi karyawan.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melakukan pelatihan karyawan mengenai hygiene dan sanitasi.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Asia Afrika No. 45, Kota Bandung',
                'lokasi_kota_id' => $kotas['Kota Bandung'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(25),
                'tanggal_selesai' => Carbon::now()->subDays(20),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Pemeriksaan laboratorium menunjukkan hasil normal untuk kentang.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Ahmad Yani No. 234, Kota Semarang',
                'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(22),
                'tanggal_selesai' => Carbon::now()->subDays(17),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Kualitas produk umbi dalam kondisi baik, sesuai standar.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Diponegoro No. 56, Kota Malang',
                'lokasi_kota_id' => $kotas['Kota Malang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(28),
                'tanggal_selesai' => Carbon::now()->subDays(23),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Ubi jalar dalam kondisi baik, tidak ada ditemukan masalah.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Raya Pajajaran No. 123, Kota Bogor',
                'lokasi_kota_id' => $kotas['Kota Bogor'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(30),
                'tanggal_selesai' => Carbon::now()->subDays(25),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, sesuai standar pangan.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Soekarno Hatta No. 345, Kota Semarang',
                'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(35),
                'tanggal_selesai' => Carbon::now()->subDays(30),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Kentang dalam kondisi baik, sesuai standar.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Tunjungan No. 678, Kota Surabaya',
                'lokasi_kota_id' => $kotas['Kota Surabaya'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(32),
                'tanggal_selesai' => Carbon::now()->subDays(27),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, tidak ada ditemukan masalah.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Merdeka No. 901, Kota Bandung',
                'lokasi_kota_id' => $kotas['Kota Bandung'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(38),
                'tanggal_selesai' => Carbon::now()->subDays(33),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Ubi jalar dalam kondisi baik, sesuai standar.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Pahlawan No. 234, Kota Semarang',
                'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(40),
                'tanggal_selesai' => Carbon::now()->subDays(35),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, sesuai standar pangan.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Basuki Rahmat No. 345, Kota Malang',
                'lokasi_kota_id' => $kotas['Kota Malang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(42),
                'tanggal_selesai' => Carbon::now()->subDays(37),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Kentang dalam kondisi baik, tidak ada ditemukan masalah.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Raya Bogor Km. 30, Kota Depok',
                'lokasi_kota_id' => $kotas['Kota Depok'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(45),
                'tanggal_selesai' => Carbon::now()->subDays(40),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, sesuai standar.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Sudirman No. 567, Kota Semarang',
                'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(48),
                'tanggal_selesai' => Carbon::now()->subDays(43),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Kentang dalam kondisi baik, sesuai standar pangan.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Tunjungan No. 890, Kota Surabaya',
                'lokasi_kota_id' => $kotas['Kota Surabaya'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(50),
                'tanggal_selesai' => Carbon::now()->subDays(45),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, tidak ada ditemukan masalah.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Asia Afrika No. 678, Kota Bandung',
                'lokasi_kota_id' => $kotas['Kota Bandung'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(52),
                'tanggal_selesai' => Carbon::now()->subDays(47),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Ubi jalar dalam kondisi baik, sesuai standar.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Pemuda No. 901, Kota Semarang',
                'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(55),
                'tanggal_selesai' => Carbon::now()->subDays(50),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, sesuai standar pangan.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Gajah Mada No. 123, Kota Surabaya',
                'lokasi_kota_id' => $kotas['Kota Surabaya'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(58),
                'tanggal_selesai' => Carbon::now()->subDays(53),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Kentang dalam kondisi baik, tidak ada ditemukan masalah.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Raya Pajajaran No. 456, Kota Bogor',
                'lokasi_kota_id' => $kotas['Kota Bogor'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Barat'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(60),
                'tanggal_selesai' => Carbon::now()->subDays(55),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, sesuai standar.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjabar@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Ahmad Yani No. 789, Kota Semarang',
                'lokasi_kota_id' => $kotas['Kota Semarang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Tengah'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(65),
                'tanggal_selesai' => Carbon::now()->subDays(60),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP035'] ?? null,
                'hasil_pengawasan' => 'Ubi jalar dalam kondisi baik, tidak ada ditemukan masalah.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Tidak ada tindakan khusus yang diperlukan.',
                'is_active' => true,
                'created_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjateng@panganaman.my.id'] ?? null,
            ],
            [
                'id' => Str::uuid(),
                'user_id_initiator' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'lokasi_alamat' => 'Jl. Diponegoro No. 345, Kota Malang',
                'lokasi_kota_id' => $kotas['Kota Malang'] ?? null,
                'lokasi_provinsi_id' => $provinsis['Jawa Timur'] ?? null,
                'tanggal_mulai' => Carbon::now()->subDays(70),
                'tanggal_selesai' => Carbon::now()->subDays(65),
                'jenis_psat_id' => $jenisPangan['JP002'] ?? null,
                'produk_psat_id' => $bahanPangan['BP135'] ?? null,
                'hasil_pengawasan' => 'Produk umbi dalam kondisi baik, sesuai standar pangan.',
                'status' => 'SELESAI',
                'tindakan_rekomendasikan' => 'Melanjutkan praktik baik yang telah dilakukan.',
                'is_active' => true,
                'created_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
                'updated_by' => $users['kantorjatim@panganaman.my.id'] ?? null,
            ],
        ];

        // Insert pengawasan data
        foreach (array_merge($pengawasanData, $additionalPengawasanData) as $data) {
            Pengawasan::create($data);
        }
    }
}
