name: Deploy Laravel to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Notify Server via Webhook
      env:
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_TOKEN }}
      run: |
        PAYLOAD='{"ref":"${{ github.ref }}","repository":{"name":"${{ github.event.repository.name }}"}}'
        SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$WEBHOOK_SECRET" | awk '{print "sha256="$2}')

        curl -X POST \
        -H "X-Hub-Signature-256: $SIGNATURE" \
        -H "Content-Type: application/json" \
        -d "$PAYLOAD" \
        https://webhook.konsultanit.my.id/webhook
